name: Deploy app

on:
  push:
    branches: ["master"]
jobs:
  deployment-dev:
    environment: dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy digitalocean
        run: ./deploy.sh
      - name: Restart daemon
        run: sudo systemctl daemon-reload
